package com.temelio;

public class Util {

    // Swagger JSON file path
    static String SWAGGER_FILE_PATH_1 = "/Users/uday/Desktop/Assignment/problem1/src/main/java/com/temelio/swagger1.json";
    static String SWAGGER_FILE_PATH_2 = "/Users/uday/Desktop/Assignment/problem1/src/main/java/com/temelio/swagger2.json";

    static String OUTPUT_FILE_PATH = "/Users/uday/Desktop/Assignment/problem1/src/main/java/com/temelio/Output.java";


    // for first swagger.json file
    static String[] SWAGGER_JSON_1 = {
            "Nonprofit", "Address", "FiscalSponsor", "NonprofitAdditionalInfo", "NonprofitIRSData", "NonprofitMetadata",
            "OfacFlags", "OfacSdn", "PlaidData", "DeleteFileInfo", "Foundation", "FoundationUser", "NonprofitUser",
            "PresignedFile", "UploadedFile", "UserFoundationRole", "UserNonprofitRole", "AppUser", "NylasSyncRequest",
            "AdditionalContact", "FoundationNonprofitInteraction", "IRS990Details", "InteractionAdditionalInfo",
            "QBVendorDetails", "AnvilPDFAdditionalInfo", "AnvilPDFField", "Budget", "BudgetAllocation",
            "CRMConfiguration", "CRMConfigurationField", "CRMExternalConfigProperty", "ConfigurationSettings",
            "CustomEmailTemplate", "CustomGrantType", "DefaultDateSetting", "DisplayCondition", "DocumentItem",
            "ExternalReviewerConfiguration", "ExternalReviewerTableConfiguration", "FeatureSet", "FormItem",
            "FormItemOptions", "FormItemValue", "FormOptionEntity", "FoundationCRMField", "FoundationMailSettings",
            "FoundationMetadata", "FoundationMetadataTag", "FoundationQuickbooksSetting", "FoundationReviewerUser",
            "FoundationSalesforceConfiguration", "GrantStage", "GrantStageWorkflow", "GrantTypeConfiguration",
            "GranteeProfileUpdate", "GranteeProfileUpdateConfiguration", "MailChimpFoundationConfiguration",
            "MetabaseConfiguration", "MetabaseDashboardUrl", "Pipeline", "QBPaymentDestination", "QBPaymentSource",
            "QBPaymentSyncSetting", "SalesforceEntityToUpdate", "SalesforceSyncRequest", "SalesforceTokenResponse",
            "ScoringCriteria", "StageTaskTemplate", "TableDisplayCell", "TableDisplayContent", "TableDisplayRow",
            "TaskTemplateAdditionalInfo", "TemelioSalesforceFieldMapping", "NonprofitIRSUpdateRequest",
            "FormComponentSubmission", "FormItemResponseEntity", "FormPDFResponseData", "TableResponseCell",
            "TableSubmissionRow", "FoundationNonprofitCreateRequest", "UpdateAppUserRequest", "DocusignTokenResponse",
            "DocusignUserFoundationSettings", "NotificationSetting", "NylasAccessToken", "NylasUserFoundationSettings",
            "SystemNotifications", "UserBrandingSettings", "UserFoundationSettings", "UserPipelineSettings", "Faceting",
            "Pagination", "SwapIndexesParams", "Task", "TaskDetails", "TaskError", "TypoTolerance", "CandidEntityResponse",
            "DemographicsCategory", "DemographicsData", "DemographicsDetails", "DemographicsResponse",
            "DemographicsStaffLevelTotals", "DemographicsSubcategory", "DemographicsSummary", "PremierAccountingRatio",
            "PremierAccreditation", "PremierAddress", "PremierAnnualReport", "PremierBalanceSheetComposition",
            "PremierBoardLeadershipPractice", "PremierBoardOfDirector", "PremierBusinessModelIndicators",
            "PremierCapitalStructureIndicators", "PremierCategory", "PremierCharitycheck", "PremierChartingImpactAnswer",
            "PremierContractor", "PremierData", "PremierDemographics", "PremierEquityStrategies",
            "PremierExpenseComposition", "PremierF990Financial", "PremierFeedbackResponse", "PremierFinancialDocument",
            "PremierFinancialStatement", "PremierFinancialTrendsAnalysis", "PremierFinancials",
            "PremierFormerlyKnownA", "PremierForms990T", "PremierFullCostComponents", "PremierFundingSource",
            "PremierHighestPaidEmployee", "PremierKeyDataChecks", "PremierLettersOfDetermination", "PremierLiquidity",
            "PremierMostRecentYearFinancials", "PremierNaicsCode", "PremierNteeCode", "PremierOfficersDirectorsKeyEmployee",
            "PremierOperations", "PremierOrgDoesNotCollectFor", "PremierOrganizationDemographics",
            "PremierOrganizationType", "PremierOtherDocument", "PremierOtherStaff", "PremierPart10BalanceSheet",
            "PremierPart8Revenue", "PremierPart9Expenses", "PremierPcsCode", "PremierPhoto", "PremierPlatinumEvaluationDocument",
            "PremierProfileDataChangeDates", "PremierProfileSdgCode", "PremierProfitability", "PremierProgram",
            "PremierProgramPlatinumMetric", "PremierPrograms", "PremierResponse", "PremierRevenueComposition", "PremierSdg",
            "PremierSicCode", "PremierStaffLevel", "PremierStaffLevelTotals", "PremierSubcategory", "PremierSummary",
            "PremierTelephoneNumber", "PremierVideo", "PremierYear", "Exception", "Function0", "Function0Object",
            "LongRunningTask", "LongRunningTaskObject", "StackTraceElement", "Throwable", "IndexRequest",
            "AggregateDashboardResponse", "AggregateFoundationProposalSummary", "AggregateGrantAnalysis",
            "AnvilPDFFieldResponse", "AnvilPDFFieldResponses", "AnvilPaymentDetails", "Currency", "DonorActivity",
            "DonorActivityAdditionalInfo", "DonorContribution", "DonorContributionComment", "DonorData", "DonorEntity",
            "DonorRelationship", "DonorTag", "EntityDetails", "FirstFormDetails", "FormBuilder",
            "FoundationProposalSummary", "GrantAdditionalInfo", "GrantAdditionalInfoEntity", "GrantAmount",
            "GrantDuration", "GrantEligibility", "GrantFormAdditionalInfo", "GrantFormProposal", "GrantPayment",
            "GrantPaymentSummary", "GrantProposalSubmission", "GrantRefereeConfig", "GrantRefereeInfo",
            "GrantRefereeRequestConfig", "GrantRefereeRequestDetail", "GrantSubmissionSearchResponse",
            "MultiFormResponse", "MultipleFormInfo", "PaymentAdditionalInfo", "PipelineProposalSummary",
            "ProposalStageResult", "QBPaymentDetails", "SignatureOrder", "SignatureStatusDetails", "TaskAdditionalInfo",
            "TaskSourceEntity", "TaskTemplate", "TaskTemplateAssignee", "TaskTemplateResponse", "TipTapAttrs",
            "TipTapTextBlock", "UserDetails", "AggregateDashboardRequest", "DataColumn", "DataRow",
            "DataSearchResponse", "SubmissionTableResponseRetriever", "AggregateDataSearchRequest", "AwardStatistics",
            "BudgetCategoryAllocation", "BudgetCategoryYOYData", "CustomGrantTypeAllocation", "CustomGrantTypeYOYData",
            "DashboardResponse", "FiscalRange", "FiscalYearData", "FoundationTagAllocation", "GrantTypeAllocation",
            "GrantTypeYOYData", "NonprofitAmount", "TagYOYData", "YOYData", "YearlyData", "AggregateExecDashboardRequest",
            "AggregateUniversalFoundationSearchResponse", "AggregateUniversalSearchResponse", "CRMSubmissionDetails",
            "FoundationNonprofitMetadata", "FoundationSearchResponseEntity", "AggregateUniversalSearchQuery",
            "AggregateContactResponse", "AggregateFoundationCRMResponse", "AggregateContactSearchRequest", "BoardBook",
            "BoardBookSummarySheet", "BoardGrantProposal", "BoardGeneratorRequest", "BoardProposalValues",
            "DocumentFieldResponse", "BoardProposalSearchResponse", "BoardProposalSearchQuery", "AnalyticsField",
            "AnalyticsFieldSubmissionInfo", "DataSearchQuery", "AnalyticsFieldPaymentResponse", "AnalyticsFieldValue",
            "AnalyticsFieldYOYData", "AnalyticsResponse", "AnalyticsRequest", "DocumentTemplate",
            "DocumentTemplateAdditionalInfo", "AccountInfo", "DocusignSenderViewResponse", "EnvelopeRecipient",
            "EnvelopeSendRequest", "DocusignAdditionalInfo", "DocusignEnvelope", "Envelope", "Recipients", "Sender",
            "Signer", "DocusignLoginURL", "DocusignLoginRequest", "DonorRelationshipType", "DonorEntityType",
            "EligibilityConfiguration", "EligibilityEmailTemplate", "EligibilityForm", "UniversalForm",
            "ExternalReviewerDashboard", "TaskSubmission", "AssignExternalReviewerRequest", "FileMeta", "FileCopyPair",
            "Folder", "AdditionalFilterInfo", "FilterView", "FilterViewCondition", "FilterViewFilter",
            "FilterViewRename", "FilterViewSettings", "FilterViewSorting", "FilterViewVisibility",
            "EligibilityFormResponses", "NonprofitGrantPair", "NonprofitGrantSubmission", "GrantEligibilityResponse",
            "GetFoundationNonprofitUsersResponse", "FoundationPaymentField", "FoundationProposals",
            "FilteredProposalCell", "FilteredProposalColumn", "FilteredProposalRow", "GetFilteredProposalsResponse",
            "GetFilteredBulkProposalsResponse", "BulkFilterProposalsRequest", "CreateTaskReviewerRequest",
            "CRMSearchResponse", "CRMSearchQuery", "FilterOption", "SortOption", "LandingPage", "ContactsResponse",
            "ContactsRequest", "PaymentSearchResponse", "PaymentSearchQuery", "BankInfoDownloadRequest",
            "NonprofitMergeRequest", "FoundationNonprofitGrantSummary", "FoundationNonprofitPaymentSummary", "NumbersACH",
            "FoundationNotes", "AccountBasedExpenseLineDetail", "AttachableRef", "Bill", "ContactInfo", "CustomField",
            "DepositLineDetail", "DescriptionLineDetail", "DiscountLineDetail", "DiscountOverride", "EmailAddress",
            "EntityTypeRef", "GenericContactType", "GroupLineDetail", "IntuitAnyType", "ItemAdjustmentLineDetail",
            "ItemBasedExpenseLineDetail", "ItemReceiptLineDetail", "JournalEntryLineDetail", "Line", "LinkedTxn",
            "MarkupInfo", "ModificationMetaData", "PaymentLineDetail", "PhysicalAddress", "PurchaseOrderItemLineDetail",
            "QBSearchResponse", "QBSearchResponseBill", "QuickbooksNonprofitDetails", "RecurringInfo",
            "RecurringScheduleInfo", "ReferenceType", "ReimburseLineDetail", "SalesItemLineDetail",
            "SalesOrderItemLineDetail", "SubTotalLineDetail", "TDSLineDetail", "Tag", "TaxLineDetail",
            "TelephoneNumber", "TxnApprovalInfo", "TxnTaxDetail", "UOMRef", "Vendor", "VendorBankAccountDetail",
            "WebSiteAddress", "AccountBalance", "AccountBase", "AuthMetadata", "AuthSupportedMethods",
            "BankAccountDetail", "HealthIncident", "IncidentUpdate", "Institution", "InstitutionStatus",
            "PaymentInitiationMetadata", "PaymentInitiationStandingOrderMetadata", "ProductStatus",
            "ProductStatusBreakdown", "BulkNonprofitUserUpdate", "FoundationNonprofitActivity",
            "GrantSubmissionStatusChange", "NylasFolder", "NylasLabel", "NylasParticipant", "NylasThread",
            "NylasThreadGroup", "StatusChangeData", "PostmarkMessage", "PostmarkMessageEvent",
            "PostmarkMessageEventDetails", "PostmarkOutboundSearchResponse", "PostmarkRecipient", "HTMLRequest",
            "SubmissionRequest", "GrantTemplate", "BulkActionRequest", "BulkCreatePaymentRequest",
            "BulkCreateReminderRequest", "BulkCreateReportRequest", "SubmissionGranteePair",
            "GrantSubmissionSearchQuery", "SubmissionComment", "ReviewEntity", "ReviewScores", "UserReviewResponse",
            "BulkDownloadRequest", "GrantProposalSubmissionDeltaResponse", "GrantSubmissionChange", "SubmissionTasks",
            "ManualGrantLog", "GrantProposalSubmissionReminder", "NonprofitGrantRefereeStatus",
            "EntitySuggestionResponse", "ResponseEntitySuggestion", "SubmissionSuggestionResponses",
            "SuggestionResponseSource", "QuestionAnswerPair", "SuggestedResponsesRequest", "MailChimpAuthUrl",
            "MailChimpAddress", "MailChimpCampaign", "MailChimpList", "NonprofitCreateRequest", "Notification",
            "NotificationContent", "NotificationResponse", "NotificationUser", "NotificationQuery", "NylasFile",
            "NylasMessage", "NylasLoginURL", "NylasFileRequest", "PlaidLinkTokenResponse", "PlaidTokenExchangeResponse",
            "PlaidTokenExchangeRequest", "QuickbooksLoginURL", "QuickbooksLoginRequest", "Account", "QBSearchResponseAccount",
            "QBBillSearchRequest", "QBSearchResponseVendor", "QBVendorSearchRequest", "Report", "ReportSubmission",
            "SubmissionEntity", "SubmissionResponse", "CommunicationEmailTemplate", "CommunicationPortalEmail",
            "CommunicationPortalEmailNonprofit", "CommunicationPortalEmailRecipients", "CommunicationPortalGetFoundationEmailsResponse",
            "CommunicationPortalGetFoundationEmailsRequest", "CommunicationPortalGetFoundationEmailResponse",
            "DocumentItemResponse", "TaskWithSubmission", "SalesforceLoginURL", "SalesforceLoginRequest", "FoundationSearchResponse",
            "FoundationSearchQuery", "NonprofitSearchEntity", "NonprofitSearchResponse", "NonprofitSearchQuery",
            "UniversalSearchDocument", "UniversalSearchResponse", "UniversalSearchQuery", "FoundationSearchBarQuery",
            "TaskSearchResponse", "TaskSearchQuery", "TaskComment", "BulkTaskSubmissionRequest", "UserBearer",
            "GetNonprofitResult", "GetNonprofitMetadataResult", "GetNonprofitUserResult", "AnalyticsPaymentYOYData"
            ,"PDFDocumentDisplay", "BoardGrantProposalAdditionalInfo"
    };

    // for second swagger.json file
    static String[] SWAGGER_JSON_2  = {"Address", "Duration", "GrantSubmission", "Nonprofit"};
}
